import Foundation

enum DataElementCountryIdentificationCode: String, CaseIterable {
    case US = "USA"
    case CA = "CAN"
    case MX = "MEX"
    case AU = "AUS"
    case GB = "GBR"
    case DE = "DEU"
    case FR = "FRA"
    case JP = "JPN"
    case AT = "AUT"
    case BE = "BEL"
    case BR = "BRA"
    case CN = "CHN"
    case DK = "DNK"
    case ES = "ESP"
    case FI = "FIN"
    case IE = "IRL"
    case IL = "ISR"
    case IN = "IND"
    case IT = "ITA"
    case KR = "KOR"
    case NL = "NLD"
    case NZ = "NZL"
    case PH = "PHL"
    case SE = "SWE"
    case SG = "SGP"
    case ZA = "ZAF"
}
